def evaluate(name: str) -> float:
    """Entropy-ish heuristic: names with long runs of random characters.

    This is a lightweight proxy for suspect autogenerated package names.
    """
    import re
    # detect long sequences of consonants/digits
    runs = re.findall(r"[bcdfghjklmnpqrstvwxyz0-9]{5,}", name.lower())
    if runs:
        return 0.9
    return 0.0
